version: 2
jobs:
vultr_deploy_fetchsh:
  machine: true
  steps:
    - run: |
           sudo apt update && sudo apt install sshpass -y
           sudo ssh ubuntu@52.15.131.199 'ls'

workflows:
rolling_update:
  jobs:
    - vultr_deploy_fetchsh:
        filters:
          branches:
            only:
              - master
