version: 2
jobs:
  vultr_deploy_fetchsh:
    machine: true
    steps:
      - add_ssh_keys
      - run: |
           ##sudo apt update && sudo apt install sshpass -y
           eval $(ssh-agent -s)
           #ssh-add ~/.ssh/id_rsa
           ssh -v ubuntu@54.213.166.229 'ls'
           #sshpass -p 'sanjay123' ssh -t -oStrictHostKeyChecking=no ubuntu@52.15.131.199 'ls'
           #sshpass -p $abc_server_pass ssh ubuntu@52.15.131.199 'ls'

workflows:
  version: 2
  rolling_update:
    jobs:
      - vultr_deploy_fetchsh:
          filters:
             branches:
               only:
                 - master
